#- name: installing datastax enterprise
  #  apt: pkg=dse-full state=installed update-cache=yes
  #register: dse

- include_vars: "../vars/version.yml"

- name: package - install cassandra and dsc
  apt: pkg={{ item }}  state=installed
  with_items:
    - dsc30={{ cassandra_major_version }}
    - cassandra={{ cassandra_version }}
    - cassandra-tools={{ cassandra_version }}

- name: configuring datastax enterprise
  template: src=templates/cassandra.yaml dest=/etc/cassandra/cassandra.yaml
